// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuGNk9znSLFCxo-bVPKDwHFp5dQzrL6yU',
    appId: '1:643126945358:web:151504949a678fe8f1051f',
    messagingSenderId: '643126945358',
    projectId: 'invoicing-app-53d36',
    authDomain: 'invoicing-app-53d36.firebaseapp.com',
    storageBucket: 'invoicing-app-53d36.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbZbkZ-syZAfZSuEvOE8jsNkpEeqVJYos',
    appId: '1:643126945358:android:81be709b551839f6f1051f',
    messagingSenderId: '643126945358',
    projectId: 'invoicing-app-53d36',
    storageBucket: 'invoicing-app-53d36.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtaGra2WzOY5T9_PLmO5IPz-WFk3MaJ5M',
    appId: '1:643126945358:ios:43c69acea5fce063f1051f',
    messagingSenderId: '643126945358',
    projectId: 'invoicing-app-53d36',
    storageBucket: 'invoicing-app-53d36.appspot.com',
    iosClientId: '643126945358-8f5ojfjofbnap7qhf0ugdkkfernljt6v.apps.googleusercontent.com',
    iosBundleId: 'com.example.ayInvoivingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtaGra2WzOY5T9_PLmO5IPz-WFk3MaJ5M',
    appId: '1:643126945358:ios:43c69acea5fce063f1051f',
    messagingSenderId: '643126945358',
    projectId: 'invoicing-app-53d36',
    storageBucket: 'invoicing-app-53d36.appspot.com',
    iosClientId: '643126945358-8f5ojfjofbnap7qhf0ugdkkfernljt6v.apps.googleusercontent.com',
    iosBundleId: 'com.example.ayInvoivingApp',
  );
}
